version: '3.8'

services:

  db:
    container_name: fastapi-test-db
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapitest
      - POSTGRES_USER=postgres
    volumes:
      - dev-pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    container_name: fastapi-test-app
    build:
      context: ../..
      dockerfile: .docker/Dockerfile
    image: fastapi-test
    command: sh -c "/app/wait-for-it.sh postgres:5432 && flask db upgrade && python -m flask run --host=0.0.0.0"
    depends_on:
      - db
    volumes:
      - ../..:/app
    ports:
      - 8001:8000
    env_file:
      - ../../local.env
    environment:
      - PYTHONPATH=/app
      - POSTGRES_HOST=postgres
    links:
      - db:postgres

volumes:
  dev-pgdata:
    driver: local