name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies and run checks
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
        xenon --no-assert --max-average A --max-modules B --max-absolute B .
        pylint fastapi_test tests
        black --check .
        isort --check .
        mypy .
        pytest --verbose --cov fastapi_test --cov-report term-missing
