# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies and run checks
      run: |
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
#        alembic upgrade head
        xenon --no-assert --max-average A --max-modules B --max-absolute B .
        pylint fastapi-test tests
        black --check .
        isort --check .
        mypy .
        pytest --verbose --cov fastapi-test --cov-report term-missing
